# Utilisation d'une image Node.js LTS (Long Term Support)
FROM node:18-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances (y compris les devDependencies pour le mode dev)
RUN npm install

# Copier le reste du code source
COPY . .

# Exposer le port 3010
EXPOSE 3010

# Commande pour démarrer le serveur de développement Nuxt
CMD ["npm", "run", "dev"]